version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pix_user
      POSTGRES_PASSWORD: pix_pass
      POSTGRES_DB: pix
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
      - ./db/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/schema/events.sql:/docker-entrypoint-initdb.d/events.sql
      - ./db/schema/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./db/schema/pictures.sql:/docker-entrypoint-initdb.d/pictures.sql
volumes:
  psql-data:
